#!/usr/bin/env bash

mysql --user=root --password="$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS testing;
    GRANT ALL PRIVILEGES ON testing.* TO '$MYSQL_USER'@'%';

    CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;
    GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%';

    ALTER USER '$MYSQL_USER'@'%' IDENTIFIED WITH mysql_native_password BY '$MYSQL_ROOT_PASSWORD';

   
EOSQL 

# CREATE USER '$MYSQL_USER'@'%'; IDENTIFIED WITH mysql_native_password BY '$MYSQL_ROOT_PASSWORD';
#     GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USER'@'%' WITH GRANT OPTION;
#     CREATE USER '$MYSQL_USER'@'%'; IDENTIFIED WITH mysql_native_password BY '$MYSQL_ROOT_PASSWORD';
#     GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USER'@'%'; WITH GRANT OPTION;
#     #
#     CREATE DATABASE IF NOT EXISTS laravel COLLATE 'utf8_general_ci' ;
#     GRANT ALL ON laravel.* TO '$MYSQL_USER'@'%';
#     FLUSH PRIVILEGES ;